Repository Software-Engineering-2-Pixel-Studio/pixelstudio, pull requests merged in 2021-04, with the labels that each got.

#88 Tower debuffs
  LeagueOfTowers/Assets/Resources/FireTower_L1.prefab
  LeagueOfTowers/Assets/Resources/LightTower_L1.prefab
  LeagueOfTowers/Assets/Resources/Scarecrow.prefab
  LeagueOfTowers/Assets/Resources/SlowTower_L1.prefab
  LeagueOfTowers/Assets/Resources/TrainingDummy.prefab
  LeagueOfTowers/Assets/Scenes/Map.unity
  LeagueOfTowers/Assets/Scripts/CurrencyManager.cs
  LeagueOfTowers/Assets/Scripts/Debuffs.meta
  LeagueOfTowers/Assets/Scripts/Debuffs/Debuff.cs
  LeagueOfTowers/Assets/Scripts/Debuffs/Debuff.cs.meta
  LeagueOfTowers/Assets/Scripts/Debuffs/FireDebuff.cs
  LeagueOfTowers/Assets/Scripts/Debuffs/FireDebuff.cs.meta
  LeagueOfTowers/Assets/Scripts/Debuffs/LightDebuff.cs
  LeagueOfTowers/Assets/Scripts/Debuffs/LightDebuff.cs.meta
  LeagueOfTowers/Assets/Scripts/Debuffs/SlowDebuff.cs
  LeagueOfTowers/Assets/Scripts/Debuffs/SlowDebuff.cs.meta
  LeagueOfTowers/Assets/Scripts/Monster.cs
  LeagueOfTowers/Assets/Scripts/Projectile.cs
  LeagueOfTowers/Assets/Scripts/Tower.meta
  LeagueOfTowers/Assets/Scripts/Tower/FireTower.cs
  LeagueOfTowers/Assets/Scripts/Tower/FireTower.cs.meta
  LeagueOfTowers/Assets/Scripts/Tower/LightTower.cs
  LeagueOfTowers/Assets/Scripts/Tower/LightTower.cs.meta
  LeagueOfTowers/Assets/Scripts/Tower/SlowTower.cs
  LeagueOfTowers/Assets/Scripts/Tower/SlowTower.cs.meta
  LeagueOfTowers/Assets/Scripts/Tower/Tower.cs
  LeagueOfTowers/Assets/Scripts/Tower/Tower.cs.meta
  LeagueOfTowers/Assets/Scripts/TowerButton.cs
  LeagueOfTowers/Assets/Scripts/WaveManager.cs
  LeagueOfTowers/UserSettings/EditorUserSettings.asset
Labels: High Priority, enhancement, feature, game

#91 Tower upgrades and Leveling Up system
  LeagueOfTowers/Assets/Resources/LightTower_L1.prefab
  LeagueOfTowers/Assets/Resources/SlowTower_L1.prefab
  LeagueOfTowers/Assets/Scenes/Map.unity
  LeagueOfTowers/Assets/Scripts/Debuffs/Debuff.cs
  LeagueOfTowers/Assets/Scripts/Debuffs/SlowDebuff.cs
  LeagueOfTowers/Assets/Scripts/GameManager.cs
  LeagueOfTowers/Assets/Scripts/Monster.cs
  LeagueOfTowers/Assets/Scripts/SelectTowerManager.cs
  LeagueOfTowers/Assets/Scripts/Tile.cs
  LeagueOfTowers/Assets/Scripts/Tower/FireTower.cs
  LeagueOfTowers/Assets/Scripts/Tower/LightTower.cs
  LeagueOfTowers/Assets/Scripts/Tower/SlowTower.cs
  LeagueOfTowers/Assets/Scripts/Tower/Tower.cs
  LeagueOfTowers/Assets/Scripts/Tower/TowerUpgrade.cs
  LeagueOfTowers/Assets/Scripts/Tower/TowerUpgrade.cs.meta
  LeagueOfTowers/Assets/Scripts/TowerButton.cs
  LeagueOfTowers/UserSettings/EditorUserSettings.asset
Labels: High Priority, core feature, game, user story

#96 Tests
  LeagueOfTowers/Assets/Editor.meta
  LeagueOfTowers/Assets/Editor/DebuffTests.cs
  LeagueOfTowers/Assets/Editor/DebuffTests.cs.meta
  LeagueOfTowers/Assets/Editor/PointTests.cs
  LeagueOfTowers/Assets/Editor/PointTests.cs.meta
  LeagueOfTowers/Assets/Editor/TowerUpgradeTests.cs
  LeagueOfTowers/Assets/Editor/TowerUpgradeTests.cs.meta
  LeagueOfTowers/Assets/Scripts/Debuff.cs
  LeagueOfTowers/Assets/Scripts/FireDebuff.cs
  LeagueOfTowers/Assets/Scripts/SlowDebuff.cs
Labels: testing

#99 Cosmetic upgrades, enemy HP display, bugfixes and Gray buttons Currency Update
  LeagueOfTowers/Assets/Resources/FireProjectile.prefab
  LeagueOfTowers/Assets/Resources/LightProjectile.prefab
  LeagueOfTowers/Assets/Resources/Scarecrow.prefab
  LeagueOfTowers/Assets/Resources/SlowProjectile.prefab
  LeagueOfTowers/Assets/Resources/TrainingDummy.prefab
  LeagueOfTowers/Assets/Scenes/LoadingScene.unity
  LeagueOfTowers/Assets/Scenes/MainMenu.unity
  LeagueOfTowers/Assets/Scenes/Map.unity
  LeagueOfTowers/Assets/Scripts/BaseTowerScript.cs
  LeagueOfTowers/Assets/Scripts/CurrencyManager.cs
  LeagueOfTowers/Assets/Scripts/FireTowerScript.cs
  LeagueOfTowers/Assets/Scripts/LightTowerScript.cs
  LeagueOfTowers/Assets/Scripts/MonsterScript.cs
  LeagueOfTowers/Assets/Scripts/Player/PlayerController.cs
  LeagueOfTowers/Assets/Scripts/ProjectileScript.cs
  LeagueOfTowers/Assets/Scripts/SelectTowerManager.cs
  LeagueOfTowers/Assets/Scripts/SlowDebuff.cs
  LeagueOfTowers/Assets/Scripts/SlowTowerScript.cs
  LeagueOfTowers/Assets/Scripts/TowerButton.cs
  LeagueOfTowers/Assets/Scripts/TowerScript.cs
  LeagueOfTowers/UserSettings/EditorUserSettings.asset
Labels: High Priority, enhancement, feature

#100 Map
  LeagueOfTowers/Assets/Resources/Map.txt
  LeagueOfTowers/Assets/Resources/Scarecrow.prefab
  LeagueOfTowers/Assets/Resources/TrainingDummy.prefab
  LeagueOfTowers/Assets/Scenes/Map.unity
  LeagueOfTowers/Assets/Scripts/MapManager.cs
  LeagueOfTowers/UserSettings/EditorUserSettings.asset
Labels: enhancement, game

#110 Update Class Diagram For Game Scripts and Package's Scripts
  LeagueOfTowers/GameClassDiagram.cd
  LeagueOfTowers/GameClassDiagram.png
  LeagueOfTowers/PhotonRealtimeClassDiagram.cd
  LeagueOfTowers/PhotonRealtimeClassDiagram.png
  LeagueOfTowers/PhotonUnityNetworkingClassDiagram.cd
  LeagueOfTowers/PhotonUnityNetworkingClassDiagram.png
Labels: documentation

#111 Update Sequence Diagram
  LeagueOfTowers/SequenceDiagramForCOOP.png
  LeagueOfTowers/SequenceDiagramForChoosingClass.png
  LeagueOfTowers/SequenceDiagramForPrivateRoom.png
  LeagueOfTowers/SequenceDiagramForUpgradeTower.png
Labels: documentation
