Repository Software-Engineering-2-Pixel-Studio/pixelstudio, pull requests merged in 2021-02, with the labels that each got.

#16 Update README.md for Core Features
  README.md
Labels: High Priority, documentation

#19 Finished the Description of the project
  README.md
Labels: documentation

#18 updated README Added Wiki and Technologies
  README.md
Labels: documentation

#20 edited README wiki part
  README.md
Labels: documentation

#29 add documents folder with proposal.md
  .gitignore
  README.md
  documents/proposal.md
Labels: documentation

#30 Web
  README.md
  docs/logo.jpeg
  docs/logo0.jpeg
  docs/proposal.md
  web/frontend/.browserslistrc
  web/frontend/.eslintrc.js
  web/frontend/.gitignore
  web/frontend/README.md
  web/frontend/babel.config.js
  web/frontend/jest.config.js
  web/frontend/package.json
  web/frontend/public/favicon.ico
  web/frontend/public/index.html
  web/frontend/src/App.vue
  web/frontend/src/assets/logo.png
  web/frontend/src/components/HelloWorld.vue
  web/frontend/src/main.js
  web/frontend/src/router/index.js
  web/frontend/src/store/index.js
  web/frontend/src/views/About.vue
  web/frontend/src/views/Home.vue
  web/frontend/tests/unit/example.spec.js
  web/frontend/yarn.lock
Labels: documentation

#37 System Architecture
  docs/architecture.png
Labels: documentation

#51 Export the Class Diagram
  LeagueOfTowers/ClassDiagram1.cd
  LeagueOfTowers/ClassDiagram1.png
  LeagueOfTowers/UserSettings/EditorUserSettings.asset
Labels: High Priority, documentation, game

#57 Sequence diagram for Tower Upgrade and Playstyle user story
  docs/Playstyle Sequence Diagram.png
  docs/Upgrade Tower Diagram.png
Labels: High Priority, documentation

#54 Travis CI initial set-up
  .travis.yml
  client/web/package.json
  client/web/src/pages/Home.js
Labels: testing

#58 Create Coop SeqDiagram.png
  docs/Coop SeqDiagram.png
Labels: High Priority, documentation

#60 Nk seq diagram login
  client/web/package-lock.json
  client/web/package.json
  client/web/yarn.lock
  docs/SeqDiagram_Login.png
Labels: High Priority, documentation, game

#61 Update .travis.yml
  .travis.yml
Labels: High Priority, bug, testing
